### ISSUE TITLE
TODO before Friday

### ISSUE THREAD

**Issue by lamoreauxaj** [Lamoreauxaj/pa#1]
This TODO list is a summary of things we hope to get mostly done before the deadline on Friday.

- [ ] Implement core geometric postulates.
  - [x] `plane`, `sphere`, `line`, `point`
  - [x] `intersection`
  - [ ] `point_on`
  - [ ] `endpoints`, `center` (endpoints optional if below types are implemented)
  - [ ] `ray`, `arc`, `segment` (optional)
  - [ ] `binormal` (optional)
- [ ] Create wrapper functions for geometric constructs.
  - [x] Add these wrapper functions to global symbol table
  - [x] Add runtime errors to these wrappers
  - [ ] Implement printing of Figure types (probably in a reasonable JSON format)
    - [x] implement printing for plane, sphere, line, point.
- [ ] Setup the ability to test suite of Ero programs to confirm features are working.
- [ ] Implement ability to type check (optional)
  - [ ] Create global type objects.
  - [ ] Use is operator to compare types.
- [ ] Implement additional operators (some are optional)
  - [ ] OR XOR AND
  - [ ] EQUALS NOT_EQUALS NOT IS NOT IN IN LESS LESS_OR_EQUAL GREATER GREATER_OR_EQUAL
  - [ ] MINUS
  - [ ] DIVIDE TIMES IDIVIDE MOD
  - [ ] POWER
  - [ ] NOT MINUS (unary)
  - [ ] Debugging grouping expressions.
  - [ ] Implement Tuple types?
    - [ ] Consider how implementing tuples will affect storing types. Everything in the language is stored by value, but if you reassign a variable, you need to free memory associated with it. Also when creating a new variable, mallocing the memory is necessary.
    - [ ] Allow creation of tuples.
    - [ ] Implement tuple indexing.
    - [ ] Use tuples in return of constructions.
- [ ] Flush out construction implementation
  - [ ] Implement arbitrary number of arguments
  - [ ] Implement more return types. This requires tuples to be complete, so we can return a tuple as a single return value.
- [x] Create a nice presentation page on our demo. This should be relatively quick.
- [x] Create a renderer component and hook it up in `Demo.vue` in order to take the output of run code and render the geometry.
  - [x] Decide on standard object notation in JSON that should be output.
  - [x] Use WebGL/Canvas to render the shapes.

**Comment by Lamoreauxaj** [comment]
To be honest, much of these things on the todo list we're even done before Friday because we got lazy. Now that the pa is over, I'll go back and try to document all issues that are known, so we have a place to continue from.
